
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[867] =
    {   0,
       98,   96,   97,   95,   96,   97,    8,   97,   96,   97,
       96,   97,   96,   97,   96,   97,   75,   96,   97,   54,
       96,   97,   96,   97,   85,   96,   97,   86,   96,   97,
       77,   96,   97,   80,   96,   97,   64,   96,   97,   79,
       96,   97,   71,   92,   96,   97,   76,   96,   97,   91,
       96,   97,   68,   96,   97,   69,   96,   97,   82,   96,
       97,   67,   96,   97,   81,   96,   97,   93,   96,   97,
       93,   96,   97,   93,   96,   97,   93,   96,   97,   87,
       96,   97,   96,   97,   88,   96,   97,   56,   96,   97,
       72,   96,   97,   93,   96,   97,   93,   96,   97,   93,

       96,   97,   93,   96,   97,   93,   96,   97,   93,   96,
       97,   93,   96,   97,   93,   96,   97,   93,   96,   97,
       93,   96,   97,   93,   96,   97,   93,   96,   97,   93,
       96,   97,   93,   96,   97,   93,   96,   97,   93,   96,
       97,   90,   96,   97,   55,   96,   97,   89,   96,   97,
       73,   96,   97,    6,   96,   97,    7,   95,   96,   97,
        2,    7,    8,   97,    6,   96,   97,    6,   96,   97,
        6,   96,   97,    6,   96,   97,    6,   75,   96,   97,
        6,   54,   96,   97,    6,   96,   97,    6,   85,   96,
       97,    6,   86,   96,   97,    6,   77,   96,   97,    6,

       80,   96,   97,    6,   64,   96,   97,    6,   79,   96,
       97,    6,   71,   92,   96,   97,    6,   76,   96,   97,
        6,   91,   96,   97,    6,   68,   96,   97,    6,   69,
       96,   97,    6,   82,   96,   97,    6,   67,   96,   97,
        6,   81,   96,   97,    6,   93,   96,   97,    6,   93,
       96,   97,    6,   93,   96,   97,    6,   93,   96,   97,
        6,   87,   96,   97,    6,   96,   97,    6,   88,   96,
       97,    6,   56,   96,   97,    6,   72,   96,   97,    6,
       93,   96,   97,    6,   93,   96,   97,    6,   93,   96,
       97,    6,   93,   96,   97,    6,   93,   96,   97,    6,

       93,   96,   97,    6,   93,   96,   97,    6,   93,   96,
       97,    6,   93,   96,   97,    6,   93,   96,   97,    6,
       93,   96,   97,    6,   93,   96,   97,    6,   93,   96,
       97,    6,   93,   96,   97,    6,   93,   96,   97,    6,
       93,   96,   97,    6,   90,   96,   97,    6,   55,   96,
       97,    6,   89,   96,   97,    6,   73,   96,   97,   10,
       97,    9,   97,    8,   21,   94,    4,    5,   60,   59,
       66,   62,   65,   63,   78,   92,   74,   61,   92,   91,
       70,   22,   19,   23,   20,   48,   93,   93,   93,   93,
        1,   57,   93,   37,   93,   84,   93,   93,   93,   93,

       93,   93,   93,   93,   93,   93,   93,   93,   93,   42,
       93,   35,   93,   17,   93,   93,   93,   27,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   58,    6,    7,
        2,    7,    7,    2,    8,    6,   21,    6,    6,   94,
        6,    3,    4,    5,    6,    6,   60,    6,   59,    6,
        6,   66,    6,   62,    6,   65,    6,   63,    6,   78,
        6,   92,    6,    6,   74,    6,   61,    6,   92,    6,
       91,    6,    6,   70,    6,   22,    6,   19,    6,   23,
        6,   20,    6,   48,    6,   93,    6,   93,    6,   93,
        6,   93,    6,   57,    6,   93,    6,   37,   93,    6,

       84,   93,    6,   93,    6,   93,    6,   93,    6,   93,
        6,   93,    6,   93,    6,   93,    6,   93,    6,   93,
        6,   93,    6,   93,    6,   93,    6,   42,   93,    6,
       35,   93,    6,   17,   93,    6,   93,    6,   93,    6,
       27,   93,    6,   93,    6,   93,    6,   93,    6,   93,
        6,   93,    6,   93,    6,   93,    6,   93,    6,   58,
       10,    9,   51,   92,   50,   91,   53,   52,   93,   93,
       93,   25,   93,   93,   93,   93,   93,   93,   93,   83,
       93,   44,   93,   93,   93,   93,   93,   93,   93,   32,
       93,   93,   93,   12,   93,   93,   24,   93,   93,   93,

       93,   93,   31,   93,   93,   93,    2,    3,    6,   51,
        6,   92,    6,   50,    6,   91,    6,   53,    6,   52,
        6,   93,    6,   93,    6,   93,    6,   25,   93,    6,
       93,    6,   93,    6,   93,    6,   93,    6,   93,    6,
       93,    6,   83,   93,    6,   44,   93,    6,   93,    6,
       93,    6,   93,    6,   93,    6,   93,    6,   93,    6,
       32,   93,    6,   93,    6,   93,    6,   12,   93,    6,
       93,    6,   24,   93,    6,   93,    6,   93,    6,   93,
        6,   93,    6,   31,   93,    6,   93,    6,   93,   93,
       26,   93,   11,   93,   93,   93,   93,   93,   93,   33,

       93,   40,   93,   93,   43,   93,   93,   93,   38,   93,
       93,   14,   93,   93,   93,   93,   13,   93,   93,   29,
       93,    6,   93,    6,   26,   93,    6,   11,   93,    6,
       93,    6,   93,    6,   93,    6,   93,    6,   93,    6,
       33,   93,    6,   40,   93,    6,   93,    6,   43,   93,
        6,   93,    6,   93,    6,   38,   93,    6,   93,    6,
       14,   93,    6,   93,    6,   93,    6,   93,    6,   13,
       93,    6,   93,    6,   29,   93,   93,   45,   93,   15,
       93,   93,   93,   93,   93,   93,   49,   93,   39,   93,
       93,   41,   93,    6,   93,    6,   45,   93,    6,   15,

       93,    6,   93,    6,   93,    6,   93,    6,   93,    6,
       93,    6,   49,   93,    6,   39,   93,    6,   93,    6,
       41,   93,   34,   93,   93,   93,   28,   93,   93,   36,
       93,   16,   18,   47,   93,    6,   34,   93,    6,   93,
        6,   93,    6,   28,   93,    6,   93,    6,   36,   93,
        6,   47,   93,   93,   30,   93,    6,   93,    6,   30,
       93,   46,   93,    6,   46,   93
    } ;

static const flex_int16_t yy_accept[427] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   11,
       13,   15,   17,   20,   23,   25,   28,   31,   34,   37,
       40,   43,   47,   50,   53,   56,   59,   62,   65,   68,
       71,   74,   77,   80,   83,   85,   88,   91,   94,   97,
      100,  103,  106,  109,  112,  115,  118,  121,  124,  127,
      130,  133,  136,  139,  142,  145,  148,  151,  154,  157,
      161,  165,  168,  171,  174,  177,  181,  185,  188,  192,
      196,  200,  204,  208,  212,  217,  221,  225,  229,  233,
      237,  241,  245,  249,  253,  257,  261,  265,  268,  272,
      276,  280,  284,  288,  292,  296,  300,  304,  308,  312,

      316,  320,  324,  328,  332,  336,  340,  344,  348,  352,
      356,  360,  362,  364,  365,  366,  366,  367,  367,  369,
      370,  371,  371,  372,  373,  374,  375,  376,  377,  377,
      378,  379,  380,  381,  381,  382,  383,  384,  385,  386,
      387,  388,  389,  390,  391,  392,  393,  394,  396,  398,
      399,  400,  401,  402,  403,  404,  405,  406,  407,  408,
      409,  410,  412,  414,  416,  417,  418,  420,  421,  422,
      423,  424,  425,  426,  427,  428,  429,  430,  431,  433,
      433,  433,  434,  436,  438,  439,  441,  442,  442,  445,
      446,  448,  450,  451,  453,  455,  457,  459,  461,  463,

      464,  466,  468,  470,  472,  473,  475,  477,  479,  481,
      483,  485,  487,  489,  491,  493,  495,  497,  500,  503,
      505,  507,  509,  511,  513,  515,  517,  519,  521,  523,
      525,  527,  530,  533,  536,  538,  540,  543,  545,  547,
      549,  551,  553,  555,  557,  559,  561,  562,  563,  564,
      565,  566,  567,  568,  569,  570,  571,  572,  574,  575,
      576,  577,  578,  579,  580,  582,  584,  585,  586,  587,
      588,  589,  590,  592,  593,  594,  596,  596,  597,  599,
      600,  601,  602,  603,  605,  606,  607,  608,  608,  609,
      609,  609,  611,  613,  615,  617,  619,  621,  623,  625,

      627,  630,  632,  634,  636,  638,  640,  642,  645,  648,
      650,  652,  654,  656,  658,  660,  663,  665,  667,  670,
      672,  675,  677,  679,  681,  683,  686,  688,  690,  691,
      693,  695,  696,  697,  698,  699,  700,  702,  704,  705,
      707,  708,  709,  711,  712,  712,  714,  714,  715,  716,
      717,  719,  720,  722,  724,  727,  730,  732,  734,  736,
      738,  740,  743,  746,  748,  751,  753,  755,  758,  760,
      763,  765,  767,  769,  772,  774,  777,  778,  780,  782,
      783,  784,  785,  786,  787,  787,  787,  789,  791,  792,
      794,  796,  799,  802,  804,  806,  808,  810,  812,  815,

      818,  820,  823,  825,  826,  827,  829,  830,  832,  833,
      834,  836,  839,  841,  843,  846,  848,  851,  854,  855,
      857,  859,  862,  864,  867,  867
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   28,
       26,   26,   26,   26,   26,   26,   26,   29,   26,   26,
       26,   26,   26,   30,   26,   26,   26,   26,   26,   26,
       31,   32,   33,   34,   26,   35,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   26,   45,   46,   47,   48,
       49,   50,   26,   51,   52,   53,   54,   26,   55,   56,
       57,   26,   58,   59,   60,   61,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    2,    2,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[438] =
    {   0,
        0,   61,  121,  125,  584,  585,  585,  585,  580,  558,
      574,  577,  555,  554,  566,  585,  585,  111,  552,  585,
      107,  109,  114,  119,  585,  585,  117,  551,  119,    0,
      538,  524,  521,  585,  568,  585,  546,  585,   99,   99,
      107,  529,   99,  114,  522,  116,  523,  517,  514,  513,
      126,  114,  512,  126,  585,  538,  585,  585,    0,  169,
      173,  558,  536,  177,  183,  535,  534,  187,    0,    0,
      167,  533,    0,  169,  175,  177,  179,    0,    0,  180,
      532,  183,  200,  519,  505,  502,    0,  549,    0,  527,
        0,  161,  161,  172,  510,  176,  214,  503,  183,  504,

      498,  495,  494,  226,  219,  493,  173,    0,  519,    0,
        0,    0,  265,  585,  585,  535,  585,  538,  585,  585,
      585,  529,  515,  585,  585,  585,  585,  244,  518,  513,
      585,  249,  255,  516,  511,  585,  585,  585,  585,  510,
        0,  487,  484,  477,  585,  585,  491,  477,    0,  479,
      487,  490,  186,  233,  233,  185,  477,  475,  472,  473,
      472,    0,  467,  514,  466,  464,    0,  472,  471,  461,
      467,  461,  454,  466,  456,  585,    0,  288,  278,  505,
      283,  295,  585,    0,  299,    0,  305,  308,  585,  311,
        0,    0,  315,  483,    0,    0,    0,    0,  301,  486,

      481,    0,  302,  305,  484,  479,    0,    0,    0,    0,
      478,    0,  455,  452,  445,    0,  459,  445,    0,  447,
      455,  458,  283,  253,  275,  265,  445,  443,  440,  441,
      440,    0,  435,  482,  434,  432,    0,  440,  439,  429,
      435,  429,  422,  434,  424,    0,    0,  331,  585,  456,
      585,  455,  585,  585,  422,  433,  432,    0,  431,  424,
      433,  416,  417,  413,    0,    0,  424,  424,  423,  424,
      425,  424,    0,  412,  421,    0,  409,  403,  450,  406,
      401,  398,  410,    0,  404,  406,  585,  334,  585,  336,
      340,    0,  428,    0,  427,    0,    0,  394,  405,  404,

        0,  403,  396,  405,  388,  389,  385,    0,    0,  396,
      396,  395,  396,  397,  396,    0,  384,  393,    0,  376,
      423,  379,  374,  371,  383,    0,  377,  379,  381,    0,
        0,  369,  374,  366,  371,  372,    0,    0,  365,    0,
      368,  360,    0,  376,  362,    0,  366,  356,  368,  356,
        0,  366,    0,  365,    0,    0,  353,  358,  350,  355,
      356,    0,    0,  349,    0,  352,  344,    0,  360,    0,
      342,  354,  342,    0,  352,    0,  338,    0,    0,  350,
      341,  335,  341,  340,  332,  336,    0,    0,  335,    0,
      329,    0,    0,  341,  332,  326,  325,  313,    0,    0,

      287,    0,    0,  268,  234,    0,  221,    0,  585,  585,
        0,    0,  205,  157,    0,  143,    0,    0,  143,    0,
      121,    0,    0,    0,  585,  345,  348,  351,  354,  131,
      357,  360,  363,  366,  369,  372,  375
    } ;

static const flex_int16_t yy_def[438] =
    {   0,
      425,  425,  426,  426,  425,  425,  425,  425,  425,  425,
      427,  428,  425,  425,  429,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  430,
      430,  430,  430,  425,  425,  425,  425,  425,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  425,  425,  425,  425,  431,  425,
      425,  431,  431,  432,  433,  431,  431,  434,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,   83,   83,   83,  431,  431,  431,  431,
      431,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,   83,   83,   83,   83,   83,  431,  431,  431,
      431,  435,  425,  425,  425,  427,  425,  428,  425,  425,
      425,  429,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      430,  430,  430,  430,  425,  425,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  425,  431,  425,  425,  425,
      436,  425,  425,  431,  432,  431,  433,  437,  425,  433,
      431,  431,  434,  431,  431,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,   83,   83,   83,   83,  431,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,  431,  435,  425,  425,  425,
      425,  425,  425,  425,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  425,  430,  430,  430,
      430,  430,  430,  430,  430,  430,  425,  436,  425,  436,
      437,  431,  431,  431,  431,  431,  431,   83,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,  430,  430,
      430,  430,  430,  430,  430,  430,  430,  430,  430,  430,
      430,  430,  430,  430,  425,  430,  425,  430,  430,  430,
      430,  430,  430,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,  430,  430,  430,  430,
      430,  430,  430,  430,  425,  425,  430,  430,  430,  430,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,  430,  430,  430,  430,  430,  430,  425,  425,
      430,   83,   83,   83,   83,   83,   83,   83,  430,  430,
       83,   83,  430,   83,    0,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425
    } ;

static const flex_int16_t yy_nxt[647] =
    {   0,
        6,    7,    8,    9,    7,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   30,   46,   30,   47,   30,   48,   49,   50,
       51,   52,   53,   30,   54,   30,   30,   55,   56,   57,
       58,   59,   60,   61,   62,   60,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   80,   81,   82,   83,   83,   84,   85,
       86,   87,   88,   89,   90,   91,   92,   93,   94,   95,

       96,   97,   98,   83,   99,   83,  100,   83,  101,  102,
      103,  104,  105,  106,   83,  107,   83,   83,  108,  109,
      110,  111,  113,  113,  123,  113,  113,  113,  128,  113,
      126,  127,  130,  141,  124,  129,  132,  131,  133,  135,
      136,  137,  139,  140,  155,  134,  147,  150,  129,  151,
      148,  149,  152,  171,  156,  153,  162,  157,  134,  158,
      424,  169,  159,  163,  160,  170,  172,  164,  174,  175,
      178,  179,  180,  178,  182,  182,  181,  182,  116,  116,
      194,  116,  423,  186,  188,  189,  190,  188,  122,  122,
      195,  122,  197,  198,  199,  201,  203,  186,  204,  422,

      202,  200,  206,  207,  208,  205,  210,  211,  217,  220,
      421,  221,  218,  219,  200,  244,  245,  222,  205,  212,
      223,  225,  269,  232,  270,  212,  212,  212,  212,  212,
      233,  226,  263,  264,  234,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  227,  241,  228,
      319,  239,  229,  128,  230,  240,  248,  248,  128,  248,
      129,  242,  132,  265,  133,  129,  267,  420,  266,  182,
      182,  134,  182,  129,  268,  289,  290,  419,  129,  178,
      179,  180,  178,  308,  134,  181,  182,  182,  309,  182,

      116,  116,  312,  116,  313,  186,  188,  189,  190,  188,
      189,  291,  188,  189,  190,  188,  122,  122,  310,  122,
      199,  199,  203,  276,  204,  186,  311,  200,  200,  306,
      307,  205,  248,  248,  418,  248,  289,  290,  289,  290,
      200,  200,  189,  291,  205,  112,  112,  112,  116,  116,
      116,  118,  118,  118,  122,  122,  122,  177,  417,  177,
      185,  185,  185,  187,  187,  187,  193,  193,  193,  247,
      416,  247,  288,  288,  288,  188,  188,  188,  415,  414,
      413,  412,  411,  410,  409,  408,  407,  406,  405,  404,
      403,  402,  401,  400,  399,  398,  319,  397,  396,  395,

      394,  393,  392,  391,  356,  390,  389,  388,  387,  386,
      385,  384,  276,  383,  382,  381,  380,  379,  378,  377,
      331,  376,  375,  374,  373,  372,  371,  347,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  319,  357,  356,  355,  354,  295,  293,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  276,
      332,  331,  330,  329,  252,  250,  328,  327,  326,  319,
      325,  324,  323,  322,  321,  320,  277,  319,  318,  317,
      316,  315,  314,  305,  304,  303,  302,  301,  300,  299,

      298,  297,  296,  295,  294,  293,  292,  287,  286,  285,
      284,  276,  283,  282,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  117,
      119,  117,  246,  243,  238,  237,  236,  235,  231,  224,
      216,  145,  215,  214,  213,  209,  196,  192,  191,  184,
      183,  176,  173,  168,  167,  166,  165,  161,  154,  146,
      145,  144,  143,  142,  138,  125,  117,  121,  120,  119,
      117,  115,  114,  425,    5,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425
    } ;

static const flex_int16_t yy_chk[647] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    3,    3,   18,    3,    4,    4,   22,    4,
       21,   21,   23,  430,   18,   22,   24,   23,   24,   27,
       27,   27,   29,   29,   43,   24,   39,   40,   22,   40,
       39,   39,   41,   52,   43,   41,   46,   44,   24,   44,
      421,   51,   44,   46,   44,   51,   52,   46,   54,   54,
       60,   60,   60,   60,   61,   61,   60,   61,   64,   64,
       71,   64,  419,   64,   65,   65,   65,   65,   68,   68,
       71,   68,   74,   74,   75,   76,   77,   68,   77,  416,

       76,   75,   80,   80,   80,   77,   82,   82,   92,   93,
      414,   93,   92,   92,   75,  107,  107,   94,   77,   83,
       94,   96,  156,   99,  156,   83,   83,   83,   83,   83,
       99,   96,  153,  153,   99,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   97,  105,   97,
      413,  104,   97,  128,   97,  104,  113,  113,  132,  113,
      128,  105,  133,  154,  133,  132,  155,  407,  154,  179,
      179,  133,  179,  128,  155,  181,  181,  405,  132,  178,
      178,  178,  178,  224,  133,  178,  182,  182,  224,  182,

      185,  185,  226,  185,  226,  185,  187,  187,  187,  187,
      188,  188,  190,  190,  190,  190,  193,  193,  225,  193,
      199,  203,  204,  404,  204,  193,  225,  199,  203,  223,
      223,  204,  248,  248,  401,  248,  288,  288,  290,  290,
      199,  203,  291,  291,  204,  426,  426,  426,  427,  427,
      427,  428,  428,  428,  429,  429,  429,  431,  398,  431,
      432,  432,  432,  433,  433,  433,  434,  434,  434,  435,
      397,  435,  436,  436,  436,  437,  437,  437,  396,  395,
      394,  391,  389,  386,  385,  384,  383,  382,  381,  380,
      377,  375,  373,  372,  371,  369,  367,  366,  364,  361,

      360,  359,  358,  357,  354,  352,  350,  349,  348,  347,
      345,  344,  342,  341,  339,  336,  335,  334,  333,  332,
      329,  328,  327,  325,  324,  323,  322,  321,  320,  318,
      317,  315,  314,  313,  312,  311,  310,  307,  306,  305,
      304,  303,  302,  300,  299,  298,  295,  293,  286,  285,
      283,  282,  281,  280,  279,  278,  277,  275,  274,  272,
      271,  270,  269,  268,  267,  264,  263,  262,  261,  260,
      259,  257,  256,  255,  252,  250,  245,  244,  243,  242,
      241,  240,  239,  238,  236,  235,  234,  233,  231,  230,
      229,  228,  227,  222,  221,  220,  218,  217,  215,  214,

      213,  211,  206,  205,  201,  200,  194,  180,  175,  174,
      173,  172,  171,  170,  169,  168,  166,  165,  164,  163,
      161,  160,  159,  158,  157,  152,  151,  150,  148,  147,
      144,  143,  142,  140,  135,  134,  130,  129,  123,  122,
      118,  116,  109,  106,  103,  102,  101,  100,   98,   95,
       90,   88,   86,   85,   84,   81,   72,   67,   66,   63,
       62,   56,   53,   50,   49,   48,   47,   45,   42,   37,
       35,   33,   32,   31,   28,   19,   15,   14,   13,   12,
       11,   10,    9,    5,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,

      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  425,  425,  425,  425,  425
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[98] =
    {   0,
1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "m2.l"
#line 2 "m2.l"
    #include <bits/stdc++.h>
    using namespace std;
    #include "m2.tab.h"
    extern int yylineno;  
    vector<int> indent;

#line 868 "lex.yy.c"

#line 870 "lex.yy.c"

#define INITIAL 0
#define NEWSTATE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "m2.l"


#line 1100 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 426 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 585 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];

find_rule: /* we branch to this label when backing up */

		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 17 "m2.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 18 "m2.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 19 "m2.l"
{}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 20 "m2.l"

	YY_BREAK
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 21 "m2.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "m2.l"
{
    if (indent.back()!= 0){
        int temp=strlen(yytext);
        for(int i=0;i<temp;i++){
            unput(yytext[temp-1-i]);
        }
        BEGIN(NEWSTATE);
    }
    else{
        REJECT;
    }
    
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 36 "m2.l"
{
    if (indent.back() < yyleng) {
        indent.push_back(yyleng);
        // cout<<"INDENT"<<endl;
        return INDENT;
    } 
    else if (indent.back() > yyleng) {
        int temp=strlen(yytext);    
    for(int i=0;i<temp;i++){
        unput(yytext[temp-1-i]);
    }
        BEGIN(NEWSTATE);
    }
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 51 "m2.l"
{
    // cout<<"newline found\n";
 return NEWLINE;
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 56 "m2.l"
{
    if (!indent.empty()) 
    {
        if(indent.back()>yyleng){
            indent.pop_back();
            // cout<<"DEDENT"<<endl;
            int temp=strlen(yytext);    
            for(int i=0;i<temp;i++){
                unput(yytext[temp-1-i]);
            }
            return DEDENT;
        }
        else if(indent.back()==yyleng){
            BEGIN(INITIAL);
        }
        else{
            fprintf(stderr, "Error: Incorrect indentation on line %d\n", yylineno);
            exit(1);
        }
        
    }
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "m2.l"
{
int temp=strlen(yytext);    
    for(int i=0;i<temp;i++){
        unput(yytext[temp-1-i]);
    }
    if (indent.back() != 0) {
        indent.pop_back();
       // cout<<"DEDENT"<<endl;
        return DEDENT;
    }
    else{  
    BEGIN(INITIAL);
    }
    
}  
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NEWSTATE):
#line 95 "m2.l"
{
        if (indent.back()!= 0){
            unput(yytext[0]);
            BEGIN(NEWSTATE);
        }
        else
        {  
            // // cout<<"ENDMARKER"<<endl;
            return ENDMARKER;
        }
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 107 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    char strr[1000]="bool";
    strcpy(yylval.attr.data_type , strr);
    return BOOL;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "m2.l"
{ 
    if(yytext == "int") 
    {
        yylval.attr.size = 4;
        char strr[1000]="int";
        strcpy(yylval.attr.data_type , strr);
    }
    else if(yytext == "float") 
    {
        yylval.attr.size = 4;
        char strr[1000]="float";
        strcpy(yylval.attr.data_type , strr);
    }
    else if(yytext == "bool")
    {
        yylval.attr.size = 1;
        char strr[1000]="bool";
        strcpy(yylval.attr.data_type , strr);
    }
    strcpy(yylval.attr.lexeme , yytext);
    return PRIMITIVES;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 137 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return SELF;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 142 "m2.l"
{ 
    strcpy(yylval.attr.lexeme , yytext);
    return LIST ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 146 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return CLASS;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 151 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return INOT;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 155 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return IS;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 159 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return NI;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 164 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return LG;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 169 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return GE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 174 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return NE;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 179 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return LE;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 184 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    
    return EE;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 190 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return NOT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 195 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return AND;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 200 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return NONE;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 205 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return OR;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 210 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return EXCEPT;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 215 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return WITH;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 220 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return FINALLY;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 225 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return TRY;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 230 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return FOR;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 235 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return ELIF;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 240 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return ASSERT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 245 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return IN;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 249 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return GLOBAL;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 253 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return AS;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 257 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return FROM;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 262 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return RAISE;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 267 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return ELSE;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 272 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return WHILE;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 277 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return IF;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 282 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return EXEC;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 287 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return DEL;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 292 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return BREAK;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 297 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return CONTINUE;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 302 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return RETURN;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 307 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return RS;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 311 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return PRINT;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 316 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return FFE;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 322 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return SSE;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 328 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return RSE;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 334 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return LSE;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 340 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return BA;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 346 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return BO;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 352 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return BX;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 358 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return BXE;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 364 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return BOE;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 369 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return ANDE;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 374 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return MODE;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 380 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return DE;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 386 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return SE;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 392 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return ME;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 397 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return COM;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 403 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return PE;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 408 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return SS;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 413 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);

    // cout<<"eq found\n";
    return EQ;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 421 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    // cout<<"col found\n";
    return COL;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 427 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return SCOL;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 432 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return LS;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 438 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return FS;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 443 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return BT;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 449 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return NEG;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 455 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return FF;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 461 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return MOD;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 467 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return DIV;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 473 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return STAR;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 478 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return ARROW;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 484 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return MINUS;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 490 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return PLUS;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 496 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    // cout<<"gt found\n";
    strcpy(yylval.attr.lexeme , yytext);
    return GT;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 503 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return LT;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 508 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);lexeme.clear();
    strcpy(yylval.attr.lexeme , yytext);
    return DEF;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 514 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return AT;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 520 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return LP;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 526 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return RP;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 532 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return LB;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 538 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return RB;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 544 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return RF;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 550 "m2.l"
{
    // strcpy(yylval.attr.lexeme , yytext);
    strcpy(yylval.attr.lexeme , yytext);
    return LF;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 558 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    char strr[1000]="int";
    strcpy(yylval.attr.data_type , strr);
    return NUMBER;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 565 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    char strr[1000]="float";
    strcpy(yylval.attr.data_type , strr);
    return NUMBER;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 575 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return NAME;
}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 580 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    yylval.attr.cnt = strlen(yytext)-2;
    char strr[1000]="str";
    strcpy(yylval.attr.data_type , strr);
    return STRING;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 588 "m2.l"
{}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 591 "m2.l"
{
    strcpy(yylval.attr.lexeme , yytext);
    return UNKNOWN;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 596 "m2.l"
ECHO;
	YY_BREAK
#line 2073 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 426 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 426 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 425);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 596 "m2.l"



